### PR TITLE
Reactive ui support

### PR DESCRIPTION
**Pull request by dmytrobaida**
- switches all components to `reactiveui.blazor` library
- adds an example of user input validation (can be checked in AccountViewModel.cs file)
- adds text view with error
- adds an example of console logger (can be checked in AccountViewModel.cs file)
- adds button with support of `ICommand`
- swithes from `MainThreadScheduler` to `TaskpoolScheduler` (it works but after time it freezes page because of memory overflow)

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Just to note the core of the bounty it is for the ReactiveUI team to complete the support of Blazor with ReactiveUI. I started the support the ReactiveUI support and it needed the finalization of the implementation that the ReactiveUI team has been doing, hence we have now ReactiveUI.Blazor.. the team have been waiting to fully validate the support to claim the bounty as it is in a different repository.

**Comment by dmytrobaida** [comment]
Thanks for response. Will close that pull request

**Comment by juanfranblanco** [comment]
Sorry for the confusion!! The light explorer sample was (is) to demonstrate and start  a common ui framework that can work across Winforms, Avalonia, WinUI, Xamarin Forms, Uno and Blazor using Reactive UI.. When Blazor came out there was no full support for Reactive UI without some trickery that I did, but this was by no means complete as Async and the Scheduler was a major issue deadlocking in many places and hence no having support for Commands etc. Hence this bounty was created to enable this, as Blazor (and Uno) enable with Wasm a Web3 (browser based) solution for everyone using .Net.

**Comment by juanfranblanco** [comment]
But surely very very nice stuff using the new Reactive.Blazor this demonstrates that we have now all the support we need!

**Pull request closed without merging**
